const fs=require('fs'),path=require('path');
const root=__dirname,dir=path.join(root,'domain');
const IMG={
 vegas:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Las%20Vegas%20strip%20at%20night,%20Nevada.jpg',
 macau:'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?auto=format&fit=crop&w=2200&q=86',
 property:'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=2200&q=82',travel:'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=2200&q=82',hotel:'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=2200&q=82',car:'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=2200&q=82',food:'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=2200&q=82',pizza:'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=2200&q=82',phones:'https://images.unsplash.com/photo-1556656793-08538906a9f8?auto=format&fit=crop&w=2200&q=82',finance:'https://images.unsplash.com/photo-1563013544-824ae1b704d3?auto=format&fit=crop&w=2200&q=84',legal:'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=2200&q=82',energy:'https://images.unsplash.com/photo-1509391366360-2e959784a276?auto=format&fit=crop&w=2200&q=82',music:'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=2200&q=82',art:'https://images.unsplash.com/photo-1541961017774-22349e4a1262?auto=format&fit=crop&w=2200&q=82',fashion:'https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=2200&q=82',beauty:'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=2200&q=82',pawn:'https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?auto=format&fit=crop&w=2200&q=82',swisswatch:'https://images.unsplash.com/photo-1523170335258-f5ed11844a49?auto=format&fit=crop&w=2200&q=88',pets:'https://images.unsplash.com/photo-1450778869180-41d0601e046e?auto=format&fit=crop&w=2200&q=82',charity:'https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?auto=format&fit=crop&w=2200&q=82',architecture:'https://images.unsplash.com/photo-1487958449943-2429e8be8625?auto=format&fit=crop&w=2200&q=82',news:'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=2200&q=82',crypto:'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=2200&q=82',ireland:'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=2200&q=82',dubai:'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=2200&q=82',
 beatles:'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=2200&q=86',freddie:'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?auto=format&fit=crop&w=2200&q=84',liveaid:'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=2200&q=88',adele:'https://images.unsplash.com/photo-1524650359799-842906ca1c06?auto=format&fit=crop&w=2200&q=84',elvis:'/assets/elvis-gates.svg',gold:'https://images.unsplash.com/photo-1610375461246-83df859d849d?auto=format&fit=crop&w=2200&q=88',bond:'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=2200&q=86',football:'https://images.unsplash.com/photo-1522778119026-d647f0596c20?auto=format&fit=crop&w=2200&q=86',busker:'https://images.unsplash.com/photo-1524650359799-842906ca1c06?auto=format&fit=crop&w=2200&q=86',sealed:'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=2200&q=86',recovery:'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=2200&q=86',resale:'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=2200&q=86',dallas:'https://images.unsplash.com/photo-1531218150217-54595bc2b934?auto=format&fit=crop&w=2200&q=86'};
function pick(n){n=n.toLowerCase();
 if(/goldfinger/.test(n))return ['gold','Gold bullion, collecting and premium asset identity'];
 if(/betfree/.test(n))return ['recovery','Freedom, recovery and a life beyond gambling'];
 if(/queenliveaid/.test(n))return ['liveaid','Huge live-concert energy and cheering crowd'];
 if(/edsheeranfan/.test(n))return ['busker','An intimate acoustic fan identity'];
 if(/sealedbid/.test(n))return ['sealed','Confidential bids, tenders and private offers'];
 if(/sellfree/.test(n))return ['resale','A free-to-sell consumer marketplace identity'];
 if(/havecashnow|welend/.test(n))return ['finance','Alternative lending and fintech identity'];
 if(/jrewing|dallasfan|dallastv/.test(n))return ['dallas','Luxury Dallas and Texas-business atmosphere'];
 if(/007|bond|connery|rogermoore|danielcraig|licencetokill/.test(n))return ['bond','A cinematic espionage-inspired fan identity'];
 if(/manchester.*fan|liverpool.*fan|manutd|reddevil/.test(n))return ['football','A packed football-terrace fan identity'];
 if(/swisstime/.test(n))return ['swisswatch','A premium identity for Swiss watches and horology'];
 if(/elvis|memphian|tcbinaflash/.test(n))return ['elvis','A distinctive identity for Elvis fans and tribute performers'];
 if(/beatles|fabfour|pennylane|strawberryfields|lovemedo|pleasepleaseme/.test(n))return ['beatles','A classic British-pop inspired fan identity'];
 if(/freddie|queen|liveaid|radiogaga|breakfree|onevision/.test(n))return ['freddie','A stadium-scale identity for Freddie and Queen fan projects'];
 if(/adele/.test(n))return ['adele','An elegant music-fan identity with premium stage presence'];
 if(/imlucky.*\.888|lucky.*\.888/.test(n))return ['macau','Luck, prosperity and premium Asian nightlife'];
 if(/casino|roulette|poker|blackjack|jackpot|odds|bet|vegas|gambler|lucky/.test(n))return ['vegas','A high-energy gaming and entertainment identity'];
 if(/dubai|abu.?dhabi|uae|emirate/.test(n))return ['dubai','A premium identity for the UAE market'];
 if(/rent|rental|property|house|housing|home|estate|realt|landlord|tenant|apartment|villa|mortgage/.test(n))return ['property','Built for property, rentals and real estate'];
 if(/flight|airline|airport|aviation|fly|travel|holiday|trip|tour/.test(n))return ['travel','A first-class travel identity'];
 if(/car|auto|motor|vehicle|garage|drive|taxi|wheel/.test(n))return ['car','Driven by a stronger digital identity'];
 if(/pizza/.test(n))return ['pizza','A mouth-watering food and delivery identity'];
 if(/phone|mobile|cellular/.test(n))return ['phones','Built for mobile retail and technology'];
 if(/invest|finance|money|bank|fund|wealth|stock|trade|capital|loan|credit|cash/.test(n))return ['finance','Built for finance, investment and growth'];
 if(/crypto|bitcoin|token|coin|blockchain|nft|wallet/.test(n))return ['crypto','A modern Web3 and digital-asset identity'];
 return null;}
function walletIdeas(n){if(!/\.wallet$/.test(n))return null;const subject=n.replace(/\.wallet$/,'');let audience='your interests, business or community';if(/manchester|manutd|reddevil/.test(n))audience='your Red Devils loyalty';else if(/liverpool/.test(n))audience='your Reds loyalty';else if(/beatles|pleasepleaseme|lovemedo|pennylane|strawberryfields/.test(n))audience='your Beatles fandom';else if(/queen|freddie|onevision|radiogaga|breakfree|liveaid/.test(n))audience='your Queen and Freddie fandom';else if(/elvis|memphian|tcbinaflash/.test(n))audience='your Elvis fandom or tribute work';return [`Pay or get paid with ${n} — a memorable Web3 wallet address that is easier to share than a long string of characters and expresses ${audience}.`,`Own a distinctive digital identity without traditional annual domain renewal fees. Put ${n} on your profile, card or community page and use it whenever you want people to pay you digitally.`,`Use it today and retain it as a transferable digital asset. A memorable Web3 name can have potential resale value if another buyer later wants the identity you own.`];}
function copyFor(n){n=n.toLowerCase();const w=walletIdeas(n);if(w)return w;
 if(/goldfinger/.test(n))return ['Create a premium destination for gold collectors, bullion buyers and precious-metal enthusiasts.','Build a marketplace for collectible bars, coins, jewellery and other high-value gold pieces.','Use the memorable identity for precious-metals education, alternative assets or a specialist gold dealership.'];
 if(/betfree/.test(n))return ['Build a recovery-support identity for people choosing a life free from compulsive gambling.','Create an education and resources community focused on gambling recovery, lived experience and practical support.','Use the Web3 identity for a gambling-free community, recovery project or digital initiative centred on freedom rather than betting.'];
 if(/sellfree/.test(n))return ['Build a consumer marketplace where people list and sell unwanted items with no seller fees.','Remove selling fees to grow the audience, then monetise through advertising, promoted listings, sponsorship and commercial partnerships.','Create a local or international community marketplace for clothes, electronics, furniture and collectibles with optional premium visibility.'];
 if(/sealedbid/.test(n))return ['Create a secure platform for sealed bids on valuable assets where offers remain private until the deadline.','Build a property, tender or procurement submission service for confidential competitive offers.','Use the name for private auctions, business tenders or competitive asset sales where discretion matters.'];
 if(/havecashnow|welend/.test(n))return ['Build an alternative online lending platform for borrowers looking beyond traditional bank credit.','Create a loan marketplace or comparison service connecting applicants with suitable lenders and finance products.','Use the name for a fintech credit platform serving customers who may be underserved by conventional lending channels.'];
 if(/swisstime/.test(n))return ['Take a traditional Swiss-watch dealership online and reduce showroom overheads, creating room for sharper pricing while maintaining a premium presentation.','Build a luxury watch marketplace where dealers, specialists and collectors can list, buy and sell premium Swiss watches internationally.','Create an online-first Swiss watch outlet for selected inventory and competitive prices aimed at customers searching globally for luxury timepieces.'];
 if(/elvis.*tribute|tribute.*elvis/.test(n))return ['Be the only Elvis tribute artist in the world using this memorable Web3 address for bookings, payments and your professional digital identity.','You have invested in the costumes, sound and stage equipment; now give promoters and clients a simple Web3 address for deposits and digital payments.',"Put the address on your cards or table signs so fans can send tips after a favourite song — a playful 'Money Honey' moment for a hunka hunka burnin' love audience."];
 if(/manchester.*fan|manutd|reddevil/.test(n))return ['Build the ultimate unofficial online destination for fans of the Red Devils, with discussion, memories and supporter-created content.','Create a match-day community for fan opinion, travel, meet-ups and conversations around the club.','Use the memorable identity for an independent supporters project, podcast, newsletter or fan community without implying official affiliation.'];
 if(/liverpool.*fan/.test(n))return ['Build an unofficial destination for Reds supporters, with match discussion, memories and supporter-created content.','Create a match-day community for fan opinion, travel, meet-ups and conversations around the club.','Use the memorable identity for an independent supporters project, podcast, newsletter or fan community without implying official affiliation.'];
 if(/casino|roulette|poker|blackjack|jackpot|odds|vegas|gambler|lucky/.test(n))return ['Launch a live gaming destination covering casino games, tournaments, entertainment and community features.','Build a premium entertainment brand around rewards, events and high-value player experiences.','Create an entertainment hub combining gaming content, reviews, promotions and destination-style experiences.'];
 return null;}
let themed=0,fallback=0,updatedCopy=0;
for(const name of fs.readdirSync(dir)){const p=path.join(dir,name,'index.html');if(!fs.existsSync(p))continue;let s=fs.readFileSync(p,'utf8');const hit=pick(name);if(hit){const [key,tag]=hit,img=IMG[key];s=s.replace(/--hero:url\('[^']+'\)/,`--hero:url('${img}')`);if(s.includes('class="tagline"'))s=s.replace(/<div class="tagline">[^<]*<\/div>/,`<div class="tagline">${tag}</div>`);themed++;}else fallback++;const ideas=copyFor(name);if(ideas){let i=0;s=s.replace(/<div class="box"><strong>([^<]+)<\/strong><br>[^<]*<\/div>/g,(m,h)=>`<div class="box"><strong>${h}</strong><br>${ideas[Math.min(i++,2)]}</div>`);updatedCopy++;}fs.writeFileSync(p,s);}console.log(`Creative audit applied: ${themed} themed, ${updatedCopy} specific copy, ${fallback} neutral.`);