const fs=require('fs'),path=require('path');
const dir=path.join(__dirname,'domain');
const veganImg='https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=2200&q=88';
const veganNames=/^(govegan|livevegan)(\.|$)/i;
for(const name of fs.readdirSync(dir)){if(!veganNames.test(name))continue;const p=path.join(dir,name,'index.html');if(!fs.existsSync(p))continue;let s=fs.readFileSync(p,'utf8');s=s.replace(/--hero:url\('[^']+'\)/,`--hero:url('${veganImg}')`);if(s.includes('class="tagline"'))s=s.replace(/<div class="tagline">[^<]*<\/div>/,'<div class="tagline">The ultimate Web3 identity for a vegan lifestyle</div>');const ideas=[`Make a statement to friends and family with ${name} — a catchy vegan Web3 identity and one-of-a-kind wallet address built around your values.`,`Pay or get paid with a memorable vegan wallet address that is easier to share than a long crypto string, while showing what you stand for.`,`Own it, use it and keep it as a transferable digital asset with potential resale value, while building a vegan community, content brand or ethical business identity around the name.`];let i=0;s=s.replace(/<div class="box"><strong>([^<]+)<\/strong><br>[^<]*<\/div>/g,(m,h)=>`<div class="box"><strong>${h}</strong><br>${ideas[Math.min(i++,2)]}</div>`);fs.writeFileSync(p,s);}
const prices={'investers.zil':99,'sellyourdomain.x':4000,'thepawnshop.x':10000,'jazzman.wallet':499,'bargainholidays.x':12500,'bookingsonline.wallet':1000};
const indexPath=path.join(__dirname,'index.html');let index=fs.readFileSync(indexPath,'utf8');for(const [domain,price] of Object.entries(prices)){const escaped=domain.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');index=index.replace(new RegExp(`("domain":"${escaped}"[^}]*?"price":)\\d+`),`$1${price}`);const p=path.join(dir,domain,'index.html');if(fs.existsSync(p)){let s=fs.readFileSync(p,'utf8'),formatted='$'+price.toLocaleString('en-US');s=s.replace(/(<div class="price">)\$[\d,]+(<\/div>)/,`$1${formatted}$2`).replace(/(listed price of )\$[\d,]+/g,`$1${formatted}`).replace(/(asking price is )\$[\d,]+/g,`$1${formatted}`);fs.writeFileSync(p,s);}}fs.writeFileSync(indexPath,index);
function override(name,img,tag,ideas){const p=path.join(dir,name,'index.html');if(!fs.existsSync(p))return;let s=fs.readFileSync(p,'utf8');if(img)s=s.replace(/--hero:url\('[^']+'\)/,`--hero:url('${img}')`);if(s.includes('class="tagline"'))s=s.replace(/<div class="tagline">[^<]*<\/div>/,`<div class="tagline">${tag}</div>`);let i=0;s=s.replace(/<div class="box"><strong>([^<]+)<\/strong><br>[^<]*<\/div>/g,(m,h)=>`<div class="box"><strong>${h}</strong><br>${ideas[Math.min(i++,2)]}</div>`);fs.writeFileSync(p,s);}
override('jazzman.wallet','https://images.unsplash.com/photo-1511192336575-5a79af67a629?auto=format&fit=crop&w=2200&q=88','A memorable Web3 wallet for the working jazz musician',['Pay and get paid with Jazzman.wallet — a memorable digital identity for a jazz musician, saxophonist or working band member.','Get tips directly from your audience while you are performing. Leave a few cards on the tables and invite customers to send a digital tip to Jazzman.wallet.','Put Jazzman.wallet on your business cards, posters and social profiles for bookings, deposits and digital payments, while retaining a transferable Web3 asset with potential resale value.']);
override('bargainholidays.x','https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=2200&q=88','The perfect address for finding a bargain in the world of holidays',['Build a worldwide bargain-holiday platform helping travellers discover great-value escapes, package holidays and destination deals.','Create a last-minute booking destination for unsold hotel rooms, flights, city breaks and late-availability holiday packages at attractive prices.','Turn BargainHolidays.x into a memorable travel marketplace spanning famous destinations around the world, earning through bookings, referrals, advertising and travel partnerships.']);
override('bookingsonline.wallet',null,'A memorable Web3 payment identity for online bookings',['Give a reputable online booking platform a memorable Web3 wallet identity for paying and getting paid digitally.','Use BookingsOnline.wallet across almost any legitimate booking industry — travel, hotels, restaurants, events, entertainment, appointments, rentals or professional services — for digital payments connected with reservations.','Build the wallet address into a booking brand for deposits, customer payments and partner settlements, while retaining a transferable Web3 digital asset with potential resale value.']);
override('buyabook.crypto','https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&w=2200&q=88','A natural Web3 name for buying and discovering books',['Build an online bookstore where readers can discover and buy printed books, ebooks and independent titles.','Create a marketplace connecting authors, publishers and readers, with digital payments and crypto-friendly commerce.','Turn BuyABook.crypto into a memorable specialist book brand for recommendations, new releases, collectibles or direct-to-reader sales.']);
console.log('Protected bespoke overrides applied.');