const fs=require('fs'),path=require('path');
const root=__dirname,dir=path.join(root,'domain');
function edit(name,fn){const p=path.join(dir,name,'index.html');if(!fs.existsSync(p))return;let s=fs.readFileSync(p,'utf8');s=fn(s);fs.writeFileSync(p,s)}
function hero(s,img){return s.replace(/--hero:url\('[^']+'\)/,`--hero:url('${img}')`)}
function tag(s,t){return s.replace(/<div class="tagline">[\s\S]*?<\/div>/,`<div class="tagline">${t}</div>`)}
function copy(s,t){return s.replace(/<p class="copy">[\s\S]*?<\/p><\/article>/,`<p class="copy">${t}</p></article>`)}
function uses(s,title,boxes){const html=boxes.map(([h,b])=>`<div class="box"><strong>${h}</strong><br>${b}</div>`).join('');const replacement=`<div class="eyebrow">Commercial possibilities</div><h2>${title}</h2><div class="grid">${html}</div><div class="notice">`;let out=s.replace(/<div class="eyebrow">(?:Ideas for this name|Why this name matters|Commercial possibilities)<\/div>[\s\S]*?<div class="notice">/i,replacement);if(out===s)out=s.replace(/<div class="eyebrow">Ideas for this name<\/div>[\s\S]*?<div class="notice">/i,replacement);return out}
const P={
'lenditnow.crypto':['https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=2200&q=90','A memorable action-led identity for digital lending and DeFi','<strong>Built around an immediate customer action:</strong> LendItNow.crypto can front a lending marketplace, DeFi protocol, secured-loan service or fintech product where speed and clarity matter.',[['Digital lending platform','Consumer, SME or asset-backed lending with digital onboarding and payment.'],['DeFi & collateral','Crypto-backed loans, liquidity services or collateralised lending products.'],['Lead-generation brand','A strong call-to-action for comparison, referral and lending-intent acquisition.']]],
'sellmyphone.crypto':['https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=2200&q=90','High-intent recommerce branding for phones, trade-ins and digital payments','<strong>A customer need is built into the name:</strong> SellMyPhone.crypto is immediately understandable for phone resale, trade-in, recycling and device recommerce.',[['Phone trade-in marketplace','Buy used devices directly from consumers with instant quotes and streamlined payment.'],['Recommerce & refurbishment','Build around resale, refurbishment, recycling and device upgrades.'],['Digital payouts','Offer supported digital-asset or stablecoin payout options alongside conventional settlement.']]],
'ourmenu.crypto':['https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=2200&q=90','A friendly restaurant and hospitality identity for menus, ordering and payments','<strong>Simple, inclusive and easy to remember:</strong> OurMenu.crypto can connect menus, ordering, loyalty and payment into one customer-facing hospitality brand.',[['Digital menu platform','QR menus, table ordering and multi-location menu management.'],['Ordering & delivery','Direct ordering tools that help hospitality businesses own the customer relationship.'],['Payments & loyalty','Connect ordering with supported crypto payments, rewards or memberships.']]],
'grandhotel.x':['https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=2200&q=90','A concise luxury-hospitality brand with international appeal','<strong>Two instantly recognisable hospitality words:</strong> GrandHotel.x can serve a premium hotel, booking platform, luxury travel group or flagship property brand.',[['Luxury hotel brand','A distinctive identity for an independent luxury property or hospitality concept.'],['Booking destination','A curated booking service for grand, heritage or premium hotels.'],['Hospitality portfolio','Hotels, residences, experiences or luxury travel services under one memorable brand.']]],
'bookahotel.x':['https://images.unsplash.com/photo-1445019980597-93fa8acb246c?auto=format&fit=crop&w=2200&q=90','An exact-action travel name that tells customers what to do','<strong>Commercial intent is immediate:</strong> BookAHotel.x is a direct-response identity for hotel search, reservations, offers and accommodation comparison.',[['Hotel booking engine','A clear destination for searching and reserving accommodation.'],['Deals & comparison','Hotel price comparison, loyalty or last-minute booking services.'],['Affiliate travel brand','Monetise high-intent hotel traffic through booking partners and offers.']]],
'bookaflight.x':['https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=2200&q=90','A direct-response travel identity for flight search and booking','<strong>The customer action is the brand:</strong> BookAFlight.x can power airfare search, comparison, booking, loyalty or specialist travel services.',[['Flight search & booking','A memorable front door for airfare search and reservation technology.'],['Fare comparison','Aggregate routes, carriers and offers around a high-intent phrase.'],['Travel membership','Alerts, loyalty, premium travel or deal-club services around repeat demand.']]],
'thepawnshop.x':['https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?auto=format&fit=crop&w=2200&q=90','A memorable category identity for resale, collateral and value','<strong>The category is already in the name:</strong> ThePawnShop.x can modernise a familiar retail and lending model for online appraisal, resale and collateral services.',[['Modern pawn marketplace','Buy, sell and value jewellery, electronics, collectibles and other assets online.'],['Collateral lending','Appraisal-led secured lending or asset-backed finance services.'],['Resale & collectibles','A destination for authenticated second-hand goods and specialist collectibles.']]],
'injuryclaims.x':['https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=2200&q=90','A high-intent legal and claims identity for claimant acquisition','<strong>InjuryClaims.x is a serious commercial legal-services name:</strong> it can serve a personal-injury practice, claims-management business, claimant information service or qualified lead-generation platform.',[['Personal injury claims','A focused destination for road traffic, workplace, public-liability and other eligible injury enquiries, subject to applicable law and regulation.'],['Claimant intake & triage','Capture enquiries, explain next steps and route prospective claimants to appropriate regulated professionals.'],['Legal lead generation','A memorable acquisition brand for law firms, claims specialists and authorised service providers seeking high-intent enquiries.']]],
'investdubai.x':['/assets/dubai-premium.jpg','A premium investment identity tied to one of the world’s most visible growth markets','<strong>Investment intent plus place:</strong> InvestDubai.x can serve property, business, relocation, private-market or investor-information services focused on Dubai.',[['Property investment','Residential, commercial and off-plan opportunities for international buyers.'],['Business & relocation','Company formation, residency, professional and relocation services.'],['Investor intelligence','Market data, opportunities, guides and qualified introductions.']]],
'bargainholidays.x':['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=2200&q=90','A clear value-led travel brand for deals, packages and late availability','<strong>The promise is obvious:</strong> BargainHolidays.x can support package deals, last-minute offers, comparison, memberships and recurring seasonal travel campaigns.',[['Holiday deals','Curate discounted packages, flights, hotels and late availability.'],['Comparison & affiliate','Aggregate value-focused travel offers and partner inventory.'],['Travel deal club','Build recurring memberships, alerts and exclusive-value campaigns.']]]
};
for(const [name,[img,t,c,b]] of Object.entries(P)) edit(name,s=>uses(copy(tag(hero(s,img),t),c),'Built for a real commercial proposition',b));
const elvis=['elvisfan.wallet','elvistheking.wallet','elvistributeartist.wallet','elvistributeartist.x','elvistributeartist.crypto','iloveelvis.wallet','elvislives.wallet','elvispresleyrip.wallet','worldsgreatestelvis.x','elvisworld.crypto','elvisworld.zil','tcbinaflash.wallet'];
for(const name of elvis)edit(name,s=>{s=hero(s,'/assets/elvis-gates.svg');if(!s.includes('id="elvis-art-fix"'))s=s.replace('</head>',`<style id="elvis-art-fix">.hero{background-image:linear-gradient(90deg,rgba(3,10,19,.88),rgba(5,17,30,.18)),var(--hero)!important;background-size:cover!important;background-position:center!important;background-repeat:no-repeat!important}@media(max-width:760px){.hero{background-image:linear-gradient(180deg,rgba(3,10,19,.45),rgba(5,17,30,.72)),var(--hero)!important}}</style></head>`);return s});
const ap=path.join(root,'assets','about-mark.js');
if(fs.existsSync(ap)){let s=fs.readFileSync(ap,'utf8');s=s.replace(/src="[^"]+" alt="Mark Leen at the airport"/,`src="/assets/mark-airport-square.jpg?v=2" alt="Mark Leen at the airport"`);fs.writeFileSync(ap,s)}
console.log('Final portrait asset and Elvis visibility fixes applied.');
